---
- name: installig vim & jq 
  hosts: localhost
  become: yes
  vars:
    packages: ["vim","jq"]
    filename: "user.txt"
  tasks:
    - name: include installa packages task 
      import_task: tasks/install_packages.yml
    - name: include create file task 
      import_task: tasks/create_file.yml 
    - name: include Display content task
      import_task: tasks/display_content.yml
        