---
- name: installig vim & jq 
  hosts: localhost
  become: yes
  tasks:
    - name: Include install packages task
      import_tasks: tasks/install_packages.yml

    - name: Include create file task
      import_tasks: tasks/create_file.yml

    - name: Include display content task
      import_tasks: tasks/display_content.yml
        