---
- name: installig vim & jq 
  hosts: localhost
  become: yes
  tasks:
    - name: include installa packages task 
      import_tasks: tasks/install_packages.yml

    - name: include create file task 
      import_tasks: tasks/create_file.yml 
      
    - name: include Display content task
      import_tasks: tasks/display_content.yml
        