---
- name: installig vim & jq 
  hosts: localhost
  become: yes
  gathering_facts: no 
  vars_files:
    - group_vars/all/user_all.yml
    - group_vars/localhost/main.yml
  tasks:
    - name: include installa packages task 
      ansible.builtin.import_tasks:
        file: tasks/install_packages.yml 
    - name: create a file from template
      ansible.builtin.import_tasks:
        file: tasks/create_file.yml
    - name: display the content of user.txt
      ansible.builtin.import_tasks:
        file: tasks/display_content.yml 
  
        