---
- name: Display file content
  ansible.builtin.command:
    cmd: "cat /home/{{filename}}"
  register: file_content

- name: Show content
  ansible.builtin.debug:
    var: file_content.stdout_lines
